error:
  codemap:
    common:
      C401:
        code: 401
        value: LOGIN ERROR
      C500:
        code: 500
        value: INTERNAL SERVER ERROR
    shop:
      S400:
        code: 400
        value: 상품등록 실패
