error:
  codemap:
    common:
      S200:
        code: 200
        value: SUCCESS
      F400:
        code: 400
        value: BAD_REQUEST
    shop:
      S200:
        code: 200
        value: SUCCESS
      S500:
        code: 500
        value: INTERNAL_SERVER_ERROR
